### ISSUE TITLE
[BUG] Master may not start success in HA mode on K8s

### ISSUE THREAD

**Issue by pan3793** [alibaba/celeborn#474]
### What is the bug(with logs or screenshots)?

```
22/08/28 03:57:34 ERROR HAMasterMetaManager: Handle update partition size failed!
com.google.protobuf.ServiceException: org.apache.ratis.protocol.exceptions.ServerNotReadyException: node1@group-085C98AE2908 is not in [RUNNING]: current state is STARTING
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.ha.HARaftServer.submitRequest(HARaftServer.java:224)
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.ha.HAMasterMetaManager.handleUpdatePartitionSize(HAMasterMetaManager.java:273)
	at com.aliyun.emr.rss.service.deploy.master.Master$$anon$1.run(Master.scala:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: org.apache.ratis.protocol.exceptions.ServerNotReadyException: node1@group-085C98AE2908 is not in [RUNNING]: current state is STARTING
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.ha.HARaftServer.submitRequest(HARaftServer.java:222)
	... 9 more
Caused by: org.apache.ratis.protocol.exceptions.ServerNotReadyException: node1@group-085C98AE2908 is not in [RUNNING]: current state is STARTING
	at org.apache.ratis.server.impl.RaftServerImpl.lambda$assertLifeCycleState$9(RaftServerImpl.java:701)
	at org.apache.ratis.util.LifeCycle.assertCurrentState(LifeCycle.java:253)
	at org.apache.ratis.server.impl.RaftServerImpl.assertLifeCycleState(RaftServerImpl.java:700)
	at org.apache.ratis.server.impl.RaftServerImpl.submitClientRequestAsync(RaftServerImpl.java:790)
	at org.apache.ratis.server.impl.RaftServerImpl.lambda$null$12(RaftServerImpl.java:783)
	at org.apache.ratis.util.JavaUtils.callAsUnchecked(JavaUtils.java:115)
	at org.apache.ratis.server.impl.RaftServerImpl.lambda$executeSubmitClientRequestAsync$13(RaftServerImpl.java:783)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 3 more
```

```
22/08/28 01:44:35 ERROR AbstractMetaManager: Worker register failed
com.aliyun.emr.rss.common.exception.RssException: Exception thrown in awaitResult:
	at com.aliyun.emr.rss.common.util.ThreadUtils$.awaitResult(ThreadUtils.scala:224)
	at com.aliyun.emr.rss.common.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:74)
	at com.aliyun.emr.rss.common.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:95)
	at com.aliyun.emr.rss.common.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:103)
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.AbstractMetaManager.updateRegisterWorkerMeta(AbstractMetaManager.java:195)
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.ha.MetaHandler.handleWriteRequest(MetaHandler.java:196)
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.ha.StateMachine.runCommand(StateMachine.java:271)
	at com.aliyun.emr.rss.service.deploy.master.clustermeta.ha.StateMachine.lambda$applyTransaction$1(StateMachine.java:246)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Connecting to /10.156.135.58:41983 timed out (10000 ms)
	at com.aliyun.emr.rss.common.network.client.TransportClientFactory.internalCreateClient(TransportClientFactory.java:221)
	at com.aliyun.emr.rss.common.network.client.TransportClientFactory.createClient(TransportClientFactory.java:170)
	at com.aliyun.emr.rss.common.network.client.TransportClientFactory.createClient(TransportClientFactory.java:177)
	at com.aliyun.emr.rss.common.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:187)
	at com.aliyun.emr.rss.common.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
	at com.aliyun.emr.rss.common.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

### How to reproduce the bug?

Use the helm template to deploy and re-deploy rss on K8s w/ 3 masters and 3 workers, hostPath is used, so raft log is retained when re-deploy master, but pods' ip changed every time.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
This was noticed, our solution is to start master nodes and wait for 60 seconds to ensure all master nodes are alive and ready. 
This problem means that the worker node starts before the master nodes are ready.

**Comment by pan3793** [comment]
The failure exists consistently in dozens of minutes, do you mean the out-of-ordered startup may corrupt the master raft cluster(sounds unreasonable)?

**Comment by FMX** [comment]
After using the latest codes to test, I can not reproduce this problem.

**Comment by pan3793** [comment]
Thanks for helping to dig out. It disappeared after I re-setup, and I found there are some other issues in our K8s infrastructure, not sure if it's related. Anyway, let's leave it now.
