### ISSUE TITLE
[BUG] Main branch regression failed.

### ISSUE THREAD

**Issue by FMX** [alibaba/celeborn#941]
### What is the bug(with logs or screenshots)?
22/11/08 16:41:36 ERROR ShuffleClientImpl: Exception raised while reviving for shuffle 89 reduce 0 epoch -1.

> java.lang.NullPointerException
> 	at org.apache.celeborn.common.util.PbSerDeUtils$.toPbPartitionLocation(PbSerDeUtils.scala:247)
> 	at org.apache.celeborn.common.protocol.message.ControlMessages$Revive$.apply(ControlMessages.scala:187)
> 	at org.apache.celeborn.client.ShuffleClientImpl.revive(ShuffleClientImpl.java:402)
> 	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:476)
> 	at org.apache.celeborn.client.ShuffleClientImpl.mergeData(ShuffleClientImpl.java:779)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.closeRowWrite(HashBasedShuffleWriter.java:400)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.close(HashBasedShuffleWriter.java:430)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.write(HashBasedShuffleWriter.java:189)
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> 22/11/08 16:41:36 ERROR Executor: Exception in task 129.1 in stage 363.0 (TID 50541)
> java.io.IOException: Revive for shuffle application_1667784454945_0041-89 partitionId 0 failed.
> 	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:485)
> 	at org.apache.celeborn.client.ShuffleClientImpl.mergeData(ShuffleClientImpl.java:779)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.closeRowWrite(HashBasedShuffleWriter.java:400)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.close(HashBasedShuffleWriter.java:430)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.write(HashBasedShuffleWriter.java:189)
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> 22/11/08 16:41:36 INFO YarnCoarseGrainedExecutorBackend: Got assigned task 50696

### How to reproduce the bug?
Steps to reproduce the bug.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
> 22/11/08 16:41:35 WARN ShuffleClientImpl: It should never reach here!
> 22/11/08 16:41:35 ERROR ShuffleClientImpl: Exception raised while reviving for shuffle 89 reduce 0 epoch -1.
> java.lang.NullPointerException
> 	at org.apache.celeborn.common.util.PbSerDeUtils$.toPbPartitionLocation(PbSerDeUtils.scala:247)
> 	at org.apache.celeborn.common.protocol.message.ControlMessages$Revive$.apply(ControlMessages.scala:187)
> 	at org.apache.celeborn.client.ShuffleClientImpl.revive(ShuffleClientImpl.java:402)
> 	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:476)
> 	at org.apache.celeborn.client.ShuffleClientImpl.mergeData(ShuffleClientImpl.java:779)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.closeRowWrite(HashBasedShuffleWriter.java:400)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.close(HashBasedShuffleWriter.java:430)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.write(HashBasedShuffleWriter.java:189)
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> 22/11/08 16:41:35 ERROR Executor: Exception in task 147.0 in stage 363.0 (TID 50465)
> java.io.IOException: Revive for shuffle application_1667784454945_0041-89 partitionId 0 failed.
> 	at org.apache.celeborn.client.ShuffleClientImpl.pushOrMergeData(ShuffleClientImpl.java:485)
> 	at org.apache.celeborn.client.ShuffleClientImpl.mergeData(ShuffleClientImpl.java:779)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.closeRowWrite(HashBasedShuffleWriter.java:400)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.close(HashBasedShuffleWriter.java:430)
> 	at org.apache.spark.shuffle.celeborn.HashBasedShuffleWriter.write(HashBasedShuffleWriter.java:189)
> 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:136)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> 22/11/08 16:41:35 INFO YarnCoarseGrainedExecutorBackend: Got assigned task 50639
> 22/11/08 16:41:35 INFO Executor: Running task 126.2 in stage 363.0 (TID 50639)
